(function(){var items=<data:post.commentJso/>;var msgs=<data:post.commentMsgs/>;var config=<data:post.commentConfig/>;var cursor=null;if(items&amp;&amp;items.length&gt;0){cursor=parseInt(items[items.length-1].timestamp)+1;}
var bodyFromEntry=function(entry){if(entry.gd$extendedProperty){for(var k in entry.gd$extendedProperty){if(entry.gd$extendedProperty[k].name==&#39;blogger.contentRemoved&#39;){return&#39;&lt;span class=&quot;deleted-comment&quot;&gt;&#39;+entry.content.$t+&#39;&lt;/span&gt;&#39;;}}}
return entry.content.$t;}
var parse=function(data){cursor=null;var comments=[];if(data&amp;&amp;data.feed&amp;&amp;data.feed.entry){for(var i=0,entry;entry=data.feed.entry[i];i++){var comment={};var id=/blog-(\d+).post-(\d+)/.exec(entry.id.$t);comment.id=id?id[2]:null;comment.body=bodyFromEntry(entry);comment.timestamp=Date.parse(entry.published.$t)+&#39;&#39;;if(entry.author&amp;&amp;entry.author.constructor===Array){var auth=entry.author[0];if(auth){comment.author={name:(auth.name?auth.name.$t:undefined),profileUrl:(auth.uri?auth.uri.$t:undefined),avatarUrl:(auth.gd$image?auth.gd$image.src:undefined)};}}
if(entry.link){if(entry.link[2]){comment.link=comment.permalink=entry.link[2].href;}
if(entry.link[3]){var pid=/.*comments\/default\/(\d+)\?.*/.exec(entry.link[3].href);if(pid&amp;&amp;pid[1]){comment.parentId=pid[1];}}}
comment.deleteclass=&#39;item-control blog-admin&#39;;if(entry.gd$extendedProperty){for(var k in entry.gd$extendedProperty){if(entry.gd$extendedProperty[k].name==&#39;blogger.itemClass&#39;){comment.deleteclass+=&#39; &#39;+entry.gd$extendedProperty[k].value;}else if(entry.gd$extendedProperty[k].name==&#39;blogger.displayTime&#39;){comment.displayTime=entry.gd$extendedProperty[k].value;}}}
comments.push(comment);}}
return comments;};var paginator=function(callback){if(hasMore()){var url=config.feed+&#39;?alt=json&amp;v=2&amp;orderby=published&amp;reverse=false&amp;max-results=50&#39;;if(cursor){url+=&#39;&amp;published-min=&#39;+new Date(cursor).toISOString();}
window.bloggercomments=function(data){var parsed=parse(data);cursor=parsed.length&lt;50?null:parseInt(parsed[parsed.length-1].timestamp)+1
callback(parsed);window.bloggercomments=null;}
url+=&#39;&amp;callback=bloggercomments&#39;;var script=document.createElement(&#39;script&#39;);script.type=&#39;text/javascript&#39;;script.src=url;document.getElementsByTagName(&#39;head&#39;)[0].appendChild(script);}};var hasMore=function(){return!!cursor;};var getMeta=function(key,comment){if(&#39;iswriter&#39;==key){var matches=!!comment.author&amp;&amp;comment.author.name==config.authorName&amp;&amp;comment.author.profileUrl==config.authorUrl;return matches?&#39;true&#39;:&#39;&#39;;}else if(&#39;deletelink&#39;==key){return config.baseUri+&#39;/delete-comment.g?blogID=&#39;
+config.blogId+&#39;&amp;postID=&#39;+comment.id;}else if(&#39;deleteclass&#39;==key){return comment.deleteclass;}
return&#39;&#39;;};var replybox=null;var replyUrlParts=null;var replyParent=undefined;var onReply=function(commentId,domId){if(replybox==null){replybox=document.getElementById(&#39;comment-editor&#39;);if(replybox!=null){replybox.height=&#39;250px&#39;;replybox.style.display=&#39;block&#39;;replyUrlParts=replybox.src.split(&#39;#&#39;);}}
if(replybox&amp;&amp;(commentId!==replyParent)){document.getElementById(domId).insertBefore(replybox.parentNode,null);replybox.src=replyUrlParts[0]
+(commentId?&#39;&amp;parentID=&#39;+commentId:&#39;&#39;)
+&#39;#&#39;+replyUrlParts[1];replyParent=commentId;}};var hash=(window.location.hash||&#39;#&#39;).substring(1);var startThread,targetComment;if(/^comment-form_/.test(hash)){startThread=hash.substring(&#39;comment-form_&#39;.length);}else if(/^c[0-9]+$/.test(hash)){targetComment=hash.substring(1);}
var configJso={&#39;maxDepth&#39;:config.maxThreadDepth};var provider={&#39;id&#39;:config.postId,&#39;data&#39;:items,&#39;loadNext&#39;:paginator,&#39;hasMore&#39;:hasMore,&#39;getMeta&#39;:getMeta,&#39;onReply&#39;:onReply,&#39;rendered&#39;:true,&#39;initComment&#39;:targetComment,&#39;initReplyThread&#39;:startThread,&#39;config&#39;:configJso,&#39;messages&#39;:msgs};var render=function(){if(window.goog&amp;&amp;window.goog.comments){var holder=document.getElementById(&#39;comment-holder&#39;);window.goog.comments.render(holder,provider);}};if(window.goog&amp;&amp;window.goog.comments){render();}else{window.goog=window.goog||{};window.goog.comments=window.goog.comments||{};window.goog.comments.loadQueue=window.goog.comments.loadQueue||[];window.goog.comments.loadQueue.push(render);}})();